package com.mints.mobilehealthapplication.viewmodels

import androidx.lifecycle.ViewModel
import com.google.firebase.auth.ktx.auth
import com.google.firebase.firestore.FieldValue
import com.google.firebase.firestore.ktx.firestore
import com.google.firebase.ktx.Firebase
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * ViewModel to handle user registration process, including authentication and saving data to Firestore.
 */
class RegistrationViewModel : ViewModel() {
    private val auth = Firebase.auth
    private val db = Firebase.firestore

    // MutableStateFlow for holding user registration data
    private val _registrationData = MutableStateFlow(RegistrationData())
    // Exposed as StateFlow for observing changes
    val registrationData = _registrationData.asStateFlow()

    // MutableStateFlow for tracking the current registration state
    private val _registrationState = MutableStateFlow<RegistrationState>(RegistrationState.Initial)
    // Exposed as StateFlow for observing changes in registration state
    val registrationState = _registrationState.asStateFlow()

    /**
     * Data class holding user registration details.
     */
    data class RegistrationData(
        var email: String = "",
        var password: String = "",
        var firstName: String = "",
        var lastName: String = "",
        var dateOfBirth: String = "",
        var phoneNumber: String = "",
        var medicationName: String = "",
        var dosage: String = "",
        var frequency: String = "",
        var reminderTime: String = "",
        var theme: String = "Light", // Default theme
        var enableNotifications: Boolean = true // Default notification preference
    )

    /**
     * Sealed class representing different states of the registration process.
     */
    sealed class RegistrationState {
        data object Initial : RegistrationState() // Initial state before any action is taken
        data object Loading : RegistrationState() // State when registration is in progress
        data class Error(val message: String) : RegistrationState() // State for error with a message
        data object Success : RegistrationState() // State for successful registration
    }

    /**
     * Function to register a new user with Firebase Authentication and save additional data to Firestore.
     */
    fun registerUser() {
        // Set state to loading while registration is in progress
        _registrationState.value = RegistrationState.Loading

        val data = _registrationData.value

        // Attempt to create user with Firebase Authentication using email and password
        auth.createUserWithEmailAndPassword(data.email, data.password)
            .addOnSuccessListener { result ->
                val user = result.user
                if (user != null) {
                    // If user creation is successful, save additional user data to Firestore
                    saveUserData(user.uid, data)
                } else {
                    // Handle case where user creation failed
                    _registrationState.value = RegistrationState.Error("User creation failed")
                }
            }
            .addOnFailureListener {
                // Handle any failure in user creation
                _registrationState.value = RegistrationState.Error(it.message ?: "Registration failed")
            }
    }

    /**
     * Function to save additional user data (such as name, medication info, etc.) to Firestore.
     *
     * @param uid The unique user ID generated by Firebase Authentication
     * @param data The registration data to be saved to Firestore
     */
    private fun saveUserData(uid: String, data: RegistrationData) {
        // Prepare user data to be stored in Firestore
        val userData = hashMapOf(
            "uid" to uid,
            "email" to data.email,
            "firstName" to data.firstName,
            "lastName" to data.lastName,
            "dateOfBirth" to data.dateOfBirth,
            "phoneNumber" to data.phoneNumber,
            "medication" to hashMapOf(
                "name" to data.medicationName,
                "dosage" to data.dosage,
                "frequency" to data.frequency,
                "reminderTime" to data.reminderTime
            ),
            "preferences" to hashMapOf(
                "theme" to data.theme,
                "enableNotifications" to data.enableNotifications
            ),
            "createdAt" to FieldValue.serverTimestamp() // Automatically set server timestamp
        )

        // Save user data to Firestore
        db.collection("users").document(uid)
            .set(userData)
            .addOnSuccessListener {
                // On successful data save, update the registration state to success
                _registrationState.value = RegistrationState.Success
            }
            .addOnFailureListener {
                // On failure to save data, update the registration state to error
                _registrationState.value = RegistrationState.Error(it.message ?: "Failed to save user data")
            }
    }

    /**
     * Function to update the registration data by applying a provided update function.
     * This allows for modifying only specific fields of the registration data.
     *
     * @param update The update function to modify the RegistrationData
     */
    fun updateRegistrationData(update: RegistrationData.() -> Unit) {
        // Apply the update to the current registration data
        _registrationData.value = _registrationData.value.apply(update)
    }
}
