package com.mints.mobilehealthapplication.viewmodels

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.google.firebase.auth.ktx.auth
import com.google.firebase.ktx.Firebase
import com.mints.mobilehealthapplication.data.FireStoreRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch
import kotlinx.coroutines.tasks.await
import java.text.ParseException
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale

/**
 * ViewModel to handle user registration process, including authentication and saving data to Firestore.
 */
class RegistrationViewModel : ViewModel() {
    private val auth = Firebase.auth

    // MutableStateFlow for holding user registration data
    private val _registrationData = MutableStateFlow(RegistrationData())
    // Exposed as StateFlow for observing changes
    val registrationData = _registrationData.asStateFlow()

    // MutableStateFlow for tracking the current registration state
    private val _registrationState = MutableStateFlow<RegistrationState>(RegistrationState.Initial)
    // Exposed as StateFlow for observing changes in registration state
    val registrationState = _registrationState.asStateFlow()

    /**
     * Data class holding user registration details.
     */
    data class RegistrationData(
        var email: String = "",
        var password: String = "",
        var firstName: String = "",
        var lastName: String = "",
        var dateOfBirth: String = "",
        var phoneNumber: String = "",
        var medicationName: String = "",
        var dosage: String = "",
        var frequency: String = "",
        var reminderTime: String = "",
        var theme: String = "Light", // Default theme
        var enableNotifications: Boolean = true // Default notification preference
    )

    /**
     * Sealed class representing different states of the registration process.
     */
    sealed class RegistrationState {
        data object Initial : RegistrationState() // Initial state before any action is taken
        data object Loading : RegistrationState() // State when registration is in progress
        data class Error(val message: String) : RegistrationState() // State for error with a message
        data object Success : RegistrationState() // State for successful registration
    }

    fun isAgeValid(dobString: String): Boolean {
        val dateFormat = SimpleDateFormat("dd/MM/yyyy", Locale.UK)
        var dob: Date? = null
        try {
            dob = dateFormat.parse(dobString)
        } catch (e: ParseException) {
            e.printStackTrace()
            return false
        }

        if (dob == null) return false

        val dobCalendar = Calendar.getInstance()
        dobCalendar.time = dob

        val currentCalendar = Calendar.getInstance()

        val yearDiff = currentCalendar.get(Calendar.YEAR) - dobCalendar.get(Calendar.YEAR)
        val monthDiff = currentCalendar.get(Calendar.MONTH) - dobCalendar.get(Calendar.MONTH)
        val dayDiff = currentCalendar.get(Calendar.DAY_OF_MONTH) - dobCalendar.get(Calendar.DAY_OF_MONTH)

        val age = if (monthDiff < 0 || (monthDiff == 0 && dayDiff < 0)) {
            yearDiff - 1
        } else {
            yearDiff
        }

        return age >= 18
    }

    /**
     * Function to register a new user with Firebase Authentication and save additional data to Firestore.
     */
    fun registerUser() = viewModelScope.launch {
        _registrationState.value = RegistrationState.Loading

        val data = _registrationData.value

        try {
            // Step 1: Create user with Firebase Authentication
            val authResult = auth.createUserWithEmailAndPassword(data.email, data.password).await()
            val user = authResult.user

            if (user != null) {
                // Step 2: Save user data to Firestore using the repository
                val isSaved = FireStoreRepository.saveUserData(user.uid, data)

                if (isSaved) {
                    _registrationState.value = RegistrationState.Success
                } else {
                    _registrationState.value = RegistrationState.Error("Failed to save user data")
                }
            } else {
                _registrationState.value = RegistrationState.Error("User creation failed")
            }
        } catch (e: Exception) {
            _registrationState.value = RegistrationState.Error(e.message ?: "Registration failed")
        }
    }

    /**
     * Function to save additional user data (such as name, medication info, etc.) to Firestore.
     *
     * @param uid The unique user ID generated by Firebase Authentication
     * @param data The registration data to be saved to Firestore
     */


    /**
     * Function to update the registration data by applying a provided update function.
     * This allows for modifying only specific fields of the registration data.
     *
     * @param update The update function to modify the RegistrationData
     */
    fun updateRegistrationData(update: RegistrationData.() -> Unit) {
        // Apply the update to the current registration data
        _registrationData.value = _registrationData.value.apply(update)
    }
}
